# Generated by Django 5.1.7 on 2025-03-23 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_actor_category_genre_ratingstar_movie_movieshots_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='descriotion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(verbose_name='Примьера в мире'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='moviesapp.movie', verbose_name='фильм'),
        ),
    ]
