# Generated by Django 5.1.7 on 2025-03-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0003_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='film_genre', to='moviesapp.genre', verbose_name='жанры'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='moviesapp.actor', verbose_name='жанры'),
        ),
    ]
